name: Update cacheless bindings
on:
  workflow_dispatch:
  schedule:
    - cron: '37 5 * * *'

jobs:
  build-cacheless-bindings:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Fetch schemas
        run: scripts/generate-bindings/get-schema.sh
        env:
          BITCRAFT_SPACETIME_HOST: ${{ secrets.BITCRAFT_SPACETIME_HOST }}
          BITCRAFT_GLOBAL_MODULE: ${{ secrets.BITCRAFT_GLOBAL_MODULE }}
          BITCRAFT_REGION_MODULE: ${{ secrets.BITCRAFT_REGION_MODULE }}
          DATA_DIR: ${{ github.workspace }}/workspace/bindings
      - name: Check schema changes
        id: check-cache
        uses: actions/cache@v4
        with:
          path: |
            workspace/bindings/global_schema.json
            workspace/bindings/region_schema.json
          key: schemas-nodeindex-${{ hashFiles('workspace/bindings/global_schema.json', 'workspace/bindings/region_schema.json') }}
      - uses: actions/checkout@v4
        if: steps.check-cache.outputs.cache-hit != 'true'
        with:
          repository: BitCraftToolBox/cacheless-rust-bindings
          path: workspace/bindings/cacheless
          ref: main
          token: ${{ secrets.ACTIONS_TOKEN }}
      - name: Generate bindings
        if: steps.check-cache.outputs.cache-hit != 'true'
        run: |
          curl -fsSL https://install.spacetimedb.com | sh -s -- --yes
          spacetime version install 2.10.0
          spacetime version use 2.10.0
          ./generate.sh
        working-directory: ${{ github.workspace }}/workspace/bindings/cacheless
        env:
          BITCRAFT_SPACETIME_HOST: ${{ secrets.BITCRAFT_SPACETIME_HOST }}
          BITCRAFT_GLOBAL_MODULE: ${{ secrets.BITCRAFT_GLOBAL_MODULE }}
          BITCRAFT_REGION_MODULE: ${{ secrets.BITCRAFT_REGION_MODULE }}
      - name: Push changes
        if: steps.check-cache.outputs.cache-hit != 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.ACTIONS_TOKEN }}
        run: |
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add -A
            if ! git diff --cached --quiet; then
              git commit -m "Update bindings: $(date +%Y-%m-%d)"
              git push origin
            fi
        working-directory: ${{ github.workspace }}/workspace/bindings/cacheless
